spring:
  main:
    allow-bean-definition-overriding: true
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp.use_jdbc_metadata_defaults: false
        default_schema: equestria_telegram_bot
    open-in-view: false
  data:
    jpa:
      repositories:
        bootstrap-mode: default
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      driver-class-name: ${spring.datasource.driver-class-name}
      jdbc-url: ${spring.datasource.url}
      username: ${spring.datasource.username}
      password: ${spring.datasource.password}
      pool-name: ${HIKARI_POOL_NAME:HikariPool}
      max-lifetime: ${HIKARI_MAX_LIFE_TIME:600000}
      connection-timeout: ${HIKARI_CONNECTION_TIMEOUT:15000}
      maximum-pool-size: ${HIKARI_MAXIMUM_POOL_SIZE:5}
      idle-timeout: ${HIKARI_IDLE_TIMEOUT:200000}
      minimum-idle: ${HIKARI_MINIMUM_IDLE:2}
      schema: ${spring.jpa.properties.hibernate.default_schema}
  liquibase:
    enabled: false

telegram:
  bot:
    token: ${TELEGRAM_BOT_TOKEN}

gpt:
  token: ${GPT_TOKEN}
  temperature: ${GPT_TEMPERATURE:0.3}
  timeout-in-sec: ${GPT_TIMEOUT_IN_SEC:120}
  keep-alive-in-sec: ${GPT_KEEP_ALIVE_DURATION:5}
  time-unit: ${GPT_AI_TIME_UNIT:seconds}
  max-idle-connections: ${GPT_MAX_IDLE_CONNECTIONS:5}
  answer-history-count: ${GPT_ANSWER_HISTORY:5}

logbook:
  strategy: body-only-if-status-at-least
  minimum-status: ${LOGBOOK_MINIMUM_STATUS:200}
  format:
    style: http
  logger:
    name: API

async:
  default-pool-size: ${GPT_POOL_SIZE:5}